In [1]:
from google.colab import drive

drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [2]:
cd /content/gdrive/My Drive/Colab Notebooks

/content/gdrive/My Drive/Colab Notebooks


In [3]:
import pandas as pd

dg= pd.read_csv("gender_submission.csv")
dtest= pd.read_csv("test.csv")
dtrain= pd.read_csv("train.csv")

In [17]:
dg

Survived
0           0
1           1
2           0
3           0
4           1
..        ...
413         0
414         1
415         0
416         0
417         0

[418 rows x 1 columns]

In [5]:
dtest=dtest.drop("PassengerId",axis=1)
dtest

Pclass                                          Name     Sex   Age  \
0         3                              Kelly, Mr. James    male  34.5   
1         3              Wilkes, Mrs. James (Ellen Needs)  female  47.0   
2         2                     Myles, Mr. Thomas Francis    male  62.0   
3         3                              Wirz, Mr. Albert    male  27.0   
4         3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0   
..      ...                                           ...     ...   ...   
413       3                            Spector, Mr. Woolf    male   NaN   
414       1                  Oliva y Ocana, Dona. Fermina  female  39.0   
415       3                  Saether, Mr. Simon Sivertsen    male  38.5   
416       3                           Ware, Mr. Frederick    male   NaN   
417       3                      Peter, Master. Michael J    male   NaN   

     SibSp  Parch              Ticket      Fare Cabin Embarked  
0        0      0              330911    7.8292   NaN        Q  
1        1      0              363272    7.0000   NaN        S  
2        0      0              240276    9.6875   NaN        Q  
3        0      0              315154    8.6625   NaN        S  
4        1      1             3101298   12.2875   NaN        S  
..     ...    ...                 ...       ...   ...      ...  
413      0      0           A.5. 3236    8.0500   NaN        S  
414      0      0            PC 17758  108.9000  C105        C  
415      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416      0      0              359309    8.0500   NaN        S  
417      1      1                2668   22.3583   NaN        C  

[418 rows x 10 columns]

In [6]:
dtrain=dtrain.drop("PassengerId",axis=1)
dtrain

Survived  Pclass                                               Name  \
0           0       3                            Braund, Mr. Owen Harris   
1           1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2           1       3                             Heikkinen, Miss. Laina   
3           1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4           0       3                           Allen, Mr. William Henry   
..        ...     ...                                                ...   
886         0       2                              Montvila, Rev. Juozas   
887         1       1                       Graham, Miss. Margaret Edith   
888         0       3           Johnston, Miss. Catherine Helen "Carrie"   
889         1       1                              Behr, Mr. Karl Howell   
890         0       3                                Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1    female  38.0      1      0          PC 17599  71.2833   C85        C  
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3    female  35.0      1      0            113803  53.1000  C123        S  
4      male  35.0      0      0            373450   8.0500   NaN        S  
..      ...   ...    ...    ...               ...      ...   ...      ...  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

In [7]:
X_train = dtrain.iloc[:,1:].values
X_train

array([[3, 'Braund, Mr. Owen Harris', 'male', ..., 7.25, nan, 'S'],
       [1, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
        'female', ..., 71.2833, 'C85', 'C'],
       [3, 'Heikkinen, Miss. Laina', 'female', ..., 7.925, nan, 'S'],
       ...,
       [3, 'Johnston, Miss. Catherine Helen "Carrie"', 'female', ...,
        23.45, nan, 'S'],
       [1, 'Behr, Mr. Karl Howell', 'male', ..., 30.0, 'C148', 'C'],
       [3, 'Dooley, Mr. Patrick', 'male', ..., 7.75, nan, 'Q']],
      dtype=object)

In [31]:
y_train = dtrain.iloc[:,0].values
y_train

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [33]:
from sklearn.preprocessing import OrdinalEncoder
import numpy as np

enc = OrdinalEncoder()
enc.fit(X_train)
z=enc.transform(X_train)
z

array([[  2., 108.,   1., ...,  18.,  nan,   2.],
       [  0., 190.,   0., ..., 207.,  81.,   0.],
       [  2., 353.,   0., ...,  41.,  nan,   2.],
       ...,
       [  2., 413.,   0., ..., 131.,  nan,   2.],
       [  0.,  81.,   1., ..., 153.,  60.,   0.],
       [  2., 220.,   1., ...,  30.,  nan,   1.]])

In [35]:
zt=pd.DataFrame(z)
ztrain2 = (zt.fillna(0)).values
ztrain2

array([[  2., 108.,   1., ...,  18.,   0.,   2.],
       [  0., 190.,   0., ..., 207.,  81.,   0.],
       [  2., 353.,   0., ...,  41.,   0.,   2.],
       ...,
       [  2., 413.,   0., ..., 131.,   0.,   2.],
       [  0.,  81.,   1., ..., 153.,  60.,   0.],
       [  2., 220.,   1., ...,  30.,   0.,   1.]])

In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt


clf = LogisticRegression()
clf.fit(ztrain2, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [45]:
from sklearn.preprocessing import OrdinalEncoder
import numpy as np
yt = dtest.values
enc = OrdinalEncoder()
enc.fit(yt)
z=enc.transform(yt)
zt=pd.DataFrame(z)
ztest = (zt.fillna(0)).values
ztest

array([[  2., 206.,   1., ...,  24.,   0.,   1.],
       [  2., 403.,   0., ...,   5.,   0.,   2.],
       [  1., 269.,   1., ...,  41.,   0.,   1.],
       ...,
       [  2., 332.,   1., ...,   9.,   0.,   2.],
       [  2., 384.,   1., ...,  31.,   0.,   2.],
       [  2., 302.,   1., ...,  84.,   0.,   0.]])

In [44]:
y_pred=clf.predict(ztest)
y_pred
len(y_pred)

418

In [29]:
res=[]
for i in range(len(y_pred)):
  res.append([y_pred[i],i])
res

[[0, 0],
 [0, 1],
 [0, 2],
 [0, 3],
 [0, 4],
 [0, 5],
 [1, 6],
 [0, 7],
 [1, 8],
 [0, 9],
 [0, 10],
 [0, 11],
 [1, 12],
 [0, 13],
 [1, 14],
 [1, 15],
 [0, 16],
 [0, 17],
 [0, 18],
 [1, 19],
 [0, 20],
 [0, 21],
 [1, 22],
 [0, 23],
 [1, 24],
 [0, 25],
 [1, 26],
 [0, 27],
 [0, 28],
 [0, 29],
 [0, 30],
 [0, 31],
 [0, 32],
 [1, 33],
 [0, 34],
 [0, 35],
 [1, 36],
 [1, 37],
 [0, 38],
 [0, 39],
 [0, 40],
 [0, 41],
 [0, 42],
 [1, 43],
 [1, 44],
 [0, 45],
 [0, 46],
 [0, 47],
 [1, 48],
 [1, 49],
 [0, 50],
 [0, 51],
 [0, 52],
 [0, 53],
 [0, 54],
 [0, 55],
 [0, 56],
 [0, 57],
 [0, 58],
 [1, 59],
 [0, 60],
 [0, 61],
 [0, 62],
 [1, 63],
 [0, 64],
 [1, 65],
 [1, 66],
 [0, 67],
 [0, 68],
 [1, 69],
 [1, 70],
 [0, 71],
 [1, 72],
 [0, 73],
 [1, 74],
 [0, 75],
 [0, 76],
 [0, 77],
 [0, 78],
 [1, 79],
 [0, 80],
 [0, 81],
 [0, 82],
 [0, 83],
 [0, 84],
 [0, 85],
 [1, 86],
 [1, 87],
 [1, 88],
 [0, 89],
 [1, 90],
 [0, 91],
 [1, 92],
 [0, 93],
 [0, 94],
 [0, 95],
 [1, 96],
 [0, 97],
 [1, 98],
 [0, 99],
 [1, 100],

In [46]:
y_sample = dg.iloc[:,0].values
y_sample

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [23]:
from sklearn.metrics import accuracy_score
acc= accuracy_score(y_sample,y_pred)
acc

0.9497607655502392